[package]

name = "secp256k1"
version = "0.1.0"
authors = [ "Fan Zhang <bl4ck5unxx@gmail.com>" ]
license = "CC0-1.0"
homepage = "https://github.com/bl4ck5un/rust-secp256k1-sgx/"
repository = "https://github.com/bl4ck5un/rust-secp256k1-sgx/"
description = "SGX Port of crate `secp256k1` (v0.11.1), Rust bindings for Pieter Wuille's `libsecp256k1` library."
keywords = [ "SGX", "no_std", "secp256k1", "libsecp256k1", "bitcoin" ]
readme = "README.md"
build = "build.rs"

[lib]
name = "secp256k1"
path = "src/lib.rs"

[features]
default = []
rand = ["sgx_rand"]

[build-dependencies]
cc = "1.0.23"

[dependencies]
libc = {version = "0.2", default-features = false}

[target.'cfg(not(target_env = "sgx"))'.dependencies]
#sgx_tstd = { version = "1.0.1" }
#sgx_rand = { version = "1.0.1", optional = true }
sgx_tstd = { git = "https://github.com/baidu/rust-sgx-sdk" }
sgx_rand = { git = "https://github.com/baidu/rust-sgx-sdk", optional = true }
